apiVersion: v1
kind: Service
metadata:
  name: {{ include "spire-step-ssh.fullname" . }}-fetchca
  labels:
    {{- include "spire-step-ssh.labels" . | nindent 4 }}
    app: spire-step-ssh
    component: fetchca
spec:
  type: {{ .Values.fetchca.service.type }}
  ports:
    - port: {{ .Values.fetchca.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "spire-step-ssh.selectorLabels" . | nindent 4 }}
