{{- define "spire-step-ssh.config-provisioners" }}
type: X5C
name: "x5c@spiffe"
roots: ""
claims:
  enableSSHCA: true
disableCustomSANs: true
options:
 ssh:
   templateFile: /home/step/config/ssh_x5c.tpl
{{- end }}
{{ $ca := deepCopy (index .Values.inject.config.files "ca.json") }}
{{ $_ := set $ca.authority "provisioners" (list (include "spire-step-ssh.config-provisioners" . | fromYaml )) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spire-step-ssh.fullname" . }}-config-raw
  labels:
    {{- include "spire-step-ssh.labels" . | nindent 4 }}
data:
  "ca.json": |
    {{- $ca | toPrettyJson | nindent 4 }}
  "defaults.json": |
    {{- index .Values.inject.config.files "defaults.json" | toPrettyJson | nindent 4 }}
  "ssh_x5c.tpl": |
    {{- .Files.Get "files/ssh_x5c.tpl" | nindent 4}}

