initdbScripts:
  usertls.sql: |
    CREATE USER 'mysqlclient'@'%' REQUIRE SUBJECT '/C=US/O=SPIRE/CN=mysqlclient.default.svc.cluster.local/x500UniqueIdentifier=a753b06724b81d4a2f14f615d40550ed';

primary:
  extraFlags: "--ssl-ca=/certs/ca.pem --ssl-cert=/certs/tls.crt --ssl-key=/certs/tls.key --require-secure-transport=ON"

  initContainers:
  - name: init-tls
    image: kfox1111/misc:spiffe-helper-test2
    imagePullPolicy: Always
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
    volumeMounts:
    - name: spiffe-workload-api
      mountPath: /spiffe-workload-api
      readOnly: true
    - name: spiffe-helper-configmap
      mountPath: /etc/spiffe-helper.conf
      subPath: helper-init.conf
      readOnly: true
    - name: certdir
      mountPath: /certs

  sidecars:
  - name: refresh-tls
    image: kfox1111/misc:spiffe-helper-test2
    imagePullPolicy: Always
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
    volumeMounts:
    - name: spiffe-workload-api
      mountPath: /spiffe-workload-api
      readOnly: true
    - name: spiffe-helper-configmap
      mountPath: /etc/spiffe-helper.conf
      subPath: helper-sidecar.conf
      readOnly: true
    - name: certdir
      mountPath: /certs

  extraVolumeMounts:
  - name: certdir
    mountPath: /certs

  extraVolumes:
  - name: certdir
    emptyDir: {}
  - name: spiffe-helper
    emptyDir: {}
  - name: spiffe-helper-configmap
    configMap:
      name: mysql-spiffe-helper
  - name: spiffe-workload-api
    csi:
      driver: "csi.spiffe.io"
      readOnly: true

extraDeploy:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: mysql-spiffe-helper
  data:
    helper-init.conf: |
      exit_when_ready = true
      agent_address = "/spiffe-workload-api/spire-agent.sock"
      cmd = ""
      cmd_args = ""
      cert_dir = "/certs"
      svid_file_name = "tls.crt"
      svid_key_file_name = "tls.key"
      svid_bundle_file_name = "ca.pem"
      add_intermediates_to_bundle = true
    helper-sidecar.conf: |
      agent_address = "/spiffe-workload-api/spire-agent.sock"
      cmd = ""
      cmd_args = ""
      cert_dir = "/certs"
      renew_signal = ""
      svid_file_name = "tls.crt"
      svid_key_file_name = "tls.key"
      svid_bundle_file_name = "ca.pem"
      add_intermediates_to_bundle = true
