global:
  spire:
    upstreamSpireAddress: spire-server.spire-root-server

spire-server:
  upstreamAuthority:
    spire:
      enabled: true
      upstreamDriver: upstream.csi.spiffe.io
  controllerManager:
    identities:
      spiffeIDTemplate: spiffe://{{ .TrustDomain }}/k8s/{{ .ClusterName }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}

upstream:
  enabled: true
