global:
  spire:
    upstreamSpireAddress: spire-server.spire-root-server

spire-server:
  enabled: true
  upstreamAuthority:
    spire:
      enabled: true
      upstreamDriver: upstream.csi.spiffe.io
  controllerManager:
    enabled: true
    identities:
      defaultSpiffeIDTemplate: spiffe://{{ .TrustDomain }}/k8s/{{ .ClusterName }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}
      clusterSPIFFEIDs:
        oidc-discovery-provider:
          dnsNameTemplates:
            - oidc-discovery.{{ .TrustDomain }}

upstream:
  enabled: true
