apiVersion: v1
kind: Pod
metadata:
  name: good-test3
spec:
  containers:
  - name: nginx
    image: nginx
    command:
    - /bin/sh
    - -c
    - |
      cat > /etc/nginx/conf.d/ssl.conf <<EOF
      server {
          listen       443 ssl;
          server_name  localhost;
          ssl_certificate     /certs/tls.crt;
          ssl_certificate_key /certs/tls.key;
          location / {
              root   /usr/share/nginx/html;
              index  index.html index.htm;
          }
          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
              root   /usr/share/nginx/html;
          }
      }
      EOF
      exec nginx -g "daemon off;"
    volumeMounts:
    - name: certs
      mountPath: /certs
    ports:
    - containerPort: 443
  - name: sidecar
    image: mysql
    env:
    - name: some-setting
      value: foo
  volumes:
  - name: certs
    csi:
      driver: helper.spiffe.io
      volumeAttributes:
        # cmd and cmdArgs should only work with customSidecar
        # customSidecar and pidContainer can't be used together
        customSidecar: sidecar
        cmd: "bash"
        cmdArgs: "-c \"echo rolled\""
        svidBundleFileName: ca.pem
        svidFileName: tls.crt
        svidKeyFileName: tls.key
