{{- $fullName := include "spiffe-oidc-discovery-provider.fullname" . }}
{{- $namespace := include "spiffe-oidc-discovery-provider.namespace" . }}
{{- define "spiffe-oidc-discovery-provider.cert-manager-default-issuer" }}
{{- if not .Values.certManager.issuer.acme.email }}
{{- fail "You must specify an email address via certManager.issuer.acme.email" }}
{{- end }}
email: {{ .Values.certManager.issuer.acme.email | quote}}
server: {{ .Values.certManager.issuer.acme.server | quote}}
privateKeySecretRef:
  name: {{ include "spiffe-oidc-discovery-provider.fullname" . }}-issuer
solvers:
- http01:
    ingress: {}
{{- end }}
{{- if and .Values.certManager.enabled .Values.certManager.issuer.create }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
spec:
  acme:
    {{ mergeOverwrite (include "spiffe-oidc-discovery-provider.cert-manager-default-issuer" . | fromYaml) .Values.certManager.issuer.acme | toYaml | nindent 4 }}
{{- end }}
{{- define "spiffe-oidc-discovery-provider.cert-manager-default-cert" }}
{{- $fullName := include "spiffe-oidc-discovery-provider.fullname" . }}
dnsNames:
  {{- if ne (len .Values.certManager.certificate.dnsNames) 0 }}
  {{-   toYaml .Values.certManager.certificate.dnsNames | nindent 4 }}
  {{- else }}
  - {{ include "spire-lib.ingress-calculated-name" (dict "ingress" .Values.ingress "Values" .Values) }}
  {{- end }}
issuerRef:
  {{- with .Values.certManager.certificate.issuerRef.group }}
  group: {{ . }}
  {{- end }}
  kind: {{ default "Issuer" .Values.certManager.certificate.issuerRef.kind }}
  name: {{ default $fullName .Values.certManager.certificate.issuerRef.name }}
secretName: {{ $fullName }}-cert
{{- end }}
{{- if .Values.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}
  namespace: {{ $namespace }}
spec:
  {{ merge (include "spiffe-oidc-discovery-provider.cert-manager-default-cert" . | fromYaml) .Values.certManager.certificate | toYaml | nindent 2 }}
{{- end }}
