apiVersion: v1
kind: Service
metadata:
  name: {{ include "spiffe-oidc-discovery-provider.fullname" . }}
  namespace: {{ include "spiffe-oidc-discovery-provider.namespace" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if eq (include "spiffe-oidc-discovery-provider.tls-count" . | int) 0 }}
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    {{- else }}
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    {{- end }}
  selector:
    {{- include "spiffe-oidc-discovery-provider.selectorLabels" . | nindent 4 }}
