global:
  telemetry:
    prometheus:
      enabled: true
  spire:
    strictMode: true
    useRecommended:
      securityContexts: true
      priorityClasses: true
      namespaces: true

spire-server:
  #FIXME auto namespace serviceAccountAllowList
  nodeAttestor:
    k8sPsat:
      serviceAccountAllowList: ["spire-system:spire-agent"]
  logLevel: info

  controllerManager:
    ignoreNamespaces:
      - kube-system
      - kube-public
      - local-path-storage

spiffe-csi-driver:
  enabled: true

spire-agent:
  enabled: true
  #FIXME auto name serviceAccount name too when using recommended namespaces?
  serviceAccount:
    name: spire-agent
  logLevel: info

upstream-spire-agent:
  logLevel: info

spiffe-oidc-discovery-provider:
  enabled: true
  config:
    additionalDomains: []
  insecureScheme:
    enabled: true
