global:
  telemetry:
    prometheus:
      enabled: true
  spire:
    useRecommended:
      enabled: true

spiffe-oidc-discovery-provider:
  enabled: true
  config:
    additionalDomains: []
  insecureScheme:
    enabled: true
