global:
  telemetry:
    prometheus:
      enabled: true
  spire:
    strictMode: true
    useRecommended:
      securityContexts: true
      priorityClasses: true

spire-server:
  nodeAttestor:
    k8sPsat:
      serviceAccountAllowList: ["spire-system:spire-agent"]
  notifier:
    k8sbundle:
      namespace: spire-system
  logLevel: info

  controllerManager:
    ignoreNamespaces:
      - kube-system
      - kube-public
      - local-path-storage

spiffe-csi-driver:
  enabled: true
  namespaceOverride: spire-system

upstream-spiffe-csi-driver:
  namespaceOverride: spire-system

spire-agent:
  enabled: true
  namespaceOverride: spire-system
  serviceAccount:
    name: spire-agent
  server:
    namespaceOverride: spire-server
  logLevel: info

upstream-spire-agent:
  namespaceOverride: spire-system
  logLevel: info

spiffe-oidc-discovery-provider:
  enabled: true
  config:
    additionalDomains: []
  insecureScheme:
    enabled: true

tornjak-frontend:
  securityContext:
    #FIXME this should work with true...
    readOnlyRootFilesystem: false
