# Default values for spire-step-ssh.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global: {}

step:
  service:
    targetPort: 8443
  inject:
    enabled: false
  bootstrap:
    enabled: false
    configmaps: false
    secrets: false
  existingSecrets:
    enabled: true
    ca: true
    issuer: true
    certsAsSecret: false
    configAsSecret: false
    sshHostCa: true
    sshUserCa: true

spiffeHelper:
  image:
    registry: ghcr.io
    repository:  spiffe/spiffe-helper
    pullPolicy: IfNotPresent
    tag: "nightly@sha256:8cee346ffdcee5c996d394f1c3bb761c2c06834a0e779a78db6dc6a46fd13ae6"

nginx:
  image:
    registry: docker.io
    repository: nginxinc/nginx-unprivileged
    pullPolicy: IfNotPresent
    tag: 1.25.3-alpine

kubectl:
  image:
    registry: docker.io
    repository: rancher/kubectl
    pullPolicy: IfNotPresent
    tag: ""

yq:
  image:
    registry: docker.io
    repository: mikefarah/yq
    pullPolicy: IfNotPresent
    tag: "4.40.5"

busybox:
  image:
    registry: docker.io
    repository: busybox
    pullPolicy: IfNotPresent
    tag: "1.36.1-uclibc"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  #FIXME
  runAsUser: 0

fetchca:
  replicaCount: 1

  service:
    type: ClusterIP
    port: 443

  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: Prefix
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
